name: Docker Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker build -t killrvideo/killrvideo-integration-tests:$GITHUB_SHA  -t killrvideo/killrvideo-integration-tests:latest .
        docker login -u ${{ secrets.docker_user }} -p ${{ secrets.docker_password }}
        docker push killrvideo/killrvideo-integration-tests:$GITHUB_SHA
        docker push killrvideo/killrvideo-integration-tests:latest
